# permissions for end users to view bpfexporterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bpfexporterconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: exporter
    app.kubernetes.io/part-of: exporter
    app.kubernetes.io/managed-by: kustomize
  name: bpfexporterconfig-viewer-role
rules:
- apiGroups:
  - bpfexporterconfig.crd.k8s.test.com.apiextensions.k8s.io
  resources:
  - bpfexporterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfexporterconfig.crd.k8s.test.com.apiextensions.k8s.io
  resources:
  - bpfexporterconfigs/status
  verbs:
  - get
